-- Подзадачи v1, шаг 1: фундамент — таблица subtasks.
-----------------------------------------------------

-- Продуктовая модель:
--   * Подзадача = чек-лист-айтем внутри родительской задачи (tasks).
--   * У подзадачи нет project/status/effort/due_date/urgent/important.
--   * Подзадачи не отображаются отдельно в Today/Board/All Tasks.
--   * Вложенность второго уровня запрещена (subtasks не ссылаются друг на друга).
--   * AI-генерация подзадач сейчас не делается (только шаг 1: схема).
----------------------------------------------------------------------

-- MVP policy: зеркалит текущую модель доступа tasks (permissive true для
-- authenticated, без user_id — у tasks тоже нет user_id и нет владельца строки).
-- TODO перед публичным продуктом: добавить user ownership / user_id и ужесточить
-- RLS как на tasks, так и на subtasks.
---------------------------------------

-- Идемпотентность: миграцию можно безопасно запускать повторно через
-- Supabase SQL Editor (if not exists / drop policy if exists).

create table if not exists public.subtasks (
id bigint generated by default as identity primary key,
task_id bigint not null references public.tasks(id) on delete cascade,
text text not null,
done boolean not null default false,
position integer not null default 0,
created_at timestamptz not null default now(),
updated_at timestamptz not null default now()
);

create index if not exists subtasks_task_id_idx
on public.subtasks(task_id);

create index if not exists subtasks_task_position_idx
on public.subtasks(task_id, position);

alter table public.subtasks enable row level security;

drop policy if exists "Allow authenticated read subtasks" on public.subtasks;
create policy "Allow authenticated read subtasks"
on public.subtasks for select
to authenticated
using (true);

drop policy if exists "Allow authenticated insert subtasks" on public.subtasks;
create policy "Allow authenticated insert subtasks"
on public.subtasks for insert
to authenticated
with check (true);

drop policy if exists "Allow authenticated update subtasks" on public.subtasks;
create policy "Allow authenticated update subtasks"
on public.subtasks for update
to authenticated
using (true)
with check (true);

drop policy if exists "Allow authenticated delete subtasks" on public.subtasks;
create policy "Allow authenticated delete subtasks"
on public.subtasks for delete
to authenticated
using (true);
