-- Управляемые проекты v1: таблица public.projects.
-------------------------------------------------------

-- Продуктовая модель:
--   * Проект = карточка с slug/name/keywords/ai_instructions, управляемая из UI
--     ("Настройки проектов"): создание, редактирование, скрытие/возврат.
--   * tasks.project ПОКА остаётся text/slug (без FK на projects.id) — намеренно,
--     это решение v1, а не временный долг. project_id вводится отдельной миграцией,
--     если/когда понадобится referential integrity.
--   * Физическое удаление проекта запрещено по продукту — только is_active=false
--     ("скрыть"). DELETE policy ниже не создаётся вообще, это и есть гарантия запрета
--     на уровне БД, а не только проверка в UI.
--   * slug ДОЛЖЕН быть неизменяемым после создания — на нём держится tasks.project
--     без FK. UI обязан запрещать редактирование slug после создания строки
--     (на уровне БД это не форсируется, проверка только в приложении).
--   * slug='other' — обязательный fallback (для AI-парсинга и для отображения
--     нераспознанных/удалённых slug). UI должен запрещать is_active=false для 'other'
--     (на уровне БД это не форсируется, проверка только в приложении).

-- RLS policy:
--   v1 — single-user permissive модель, зеркалит политики tasks/subtasks
--   (без user_id, без владельца строки, SELECT/INSERT/UPDATE = true для authenticated).
--   Future multi-user: понадобится колонка user_id, UNIQUE(user_id, slug) вместо
--   глобального UNIQUE(slug), и RLS по user_id вместо permissive true.

-- Идемпотентность: миграцию можно безопасно запускать повторно
-- (if not exists / drop policy if exists / on conflict do nothing).

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text unique not null check (slug ~ '^[a-z0-9_-]+$'),
  name text not null,
  description text null,
  keywords text null,
  ai_instructions text null,
  is_active boolean not null default true,
  position int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- updated_at не обновляется сам по умолчанию при UPDATE — нужен триггер.
create or replace function public.projects_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row
execute function public.projects_set_updated_at();

alter table public.projects enable row level security;

drop policy if exists "Allow authenticated read projects" on public.projects;
create policy "Allow authenticated read projects"
on public.projects for select
to authenticated
using (true);

drop policy if exists "Allow authenticated insert projects" on public.projects;
create policy "Allow authenticated insert projects"
on public.projects for insert
to authenticated
with check (true);

drop policy if exists "Allow authenticated update projects" on public.projects;
create policy "Allow authenticated update projects"
on public.projects for update
to authenticated
using (true)
with check (true);

-- Намеренно нет DELETE policy: физическое удаление проекта запрещено по продукту.

-- Seed: перенос текущих 10 проектов из index.html (PROJECTS) и
-- parse-tasks/index.ts (ALLOWED_PROJECTS, раздел 8 системного промпта).
-- keywords взяты дословно из текста раздела 8 промпта.
-- ai_instructions = null: раздел 8 содержит только ключевые слова, не отдельные
-- инструкции по проекту — общие правила разрешения конфликтов ("человек/маркер
-- сильнее общей темы" и т.п.) остаются в статичной части промпта, а не дублируются
-- в ai_instructions каждого проекта.
-- description = null — заполняется вручную позже через UI "Настройки проектов".
insert into public.projects (slug, name, description, keywords, ai_instructions, is_active, position)
values
  ('law',      'Судебное дело',         null, 'суд, дедушка, иск, заседание, нотариус, документы по делу, юрист', null, true, 0),
  ('popcorn',  'Rush Попкорн',          null, 'Зимин, Константин, попкорн, Rush, финмодель попкорна, логотип для Зимина', null, true, 1),
  ('politics', 'Новые люди',            null, 'Новые люди, партия, депутаты, карта первых дел, политика, фракция', null, true, 2),
  ('fencing',  'Не тот Королёв',        null, 'фехтование, Не тот Королёв, Саша, тренировка, соревнования', null, true, 3),
  ('china',    'Маркетплейсы',          null, 'Ozon, Wildberries, WB, Wondersell, китайские магазины/поставщики, кабинеты продавцов, блокировки, карточки товаров', null, true, 4),
  ('istra',    'Помещение Истра',       null, 'Истра, помещение Истра, аренда Истра', null, true, 5),
  ('tma',      'AI / TMA / разработка', null, 'задачник, drawer, дизайн приложения, AI prompt, Supabase, Claude, Cursor, TMA, сайт, разработка, деплой', null, true, 6),
  ('health',   'Пётр Михайлович',       null, 'Пётр Михайлович, больница, химия, лечение, врач, здоровье родственника', null, true, 7),
  ('personal', 'Личное',                null, 'покупки, семья, дети, школа, бытовое, личные финансы, своё здоровье', null, true, 8),
  ('other',    'Разное',                null, 'всё неясное', null, true, 9)
on conflict (slug) do nothing;
